# .github/release.yml
# Modified from https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
# and https://gitmoji.dev/
changelog:
  exclude:
    labels:
      - changelog:ignore-for-release
  categories:
    - Added: ✨ New Features
      labels:
        - changelog:new-feature
    - Changed: ♻️ Changed and Improved Functionalities 
      labels:
        - changelog:enhancement
        - changelog:refactor
    - Fixed: 🐛 Bugfixes and Security Improvements
      labels:
        - changelog:bugfix
        - changelog:security
    - Removed: 🔥 Removed and Deprecated Features
      labels:
        - changelog:removal
        - changelog:deprecation
