receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317  # Default endpoint for OTLP over gRPC
      http:
        endpoint: 0.0.0.0:4318 # Default endpoint for OTLP over HTTP
exporters:
  otlphttp/swarm-jaeger:
    endpoint: ${TRACING_OPENTELEMETRY_COLLECTOR_EXPORTER_ENDPOINT}  # Adjust to your Jaeger endpoint
  otlphttp/k8s-signoz:
    endpoint: https://admin:testertestertester@opentelemetrycollector.signoz.monitoring.k8s.osparc.local:443
    tls:
      insecure: false
      insecure_skip_verify: true
  otlphttp/k8s-jaeger:
    endpoint: https://admin:testertestertester@jaeger.monitoring.k8s.osparc.local:443/api/traces
    tls:
      insecure: false
      insecure_skip_verify: true
service:
  pipelines:
    traces/swarm:
      receivers: [otlp]
      exporters: [otlphttp/swarm-jaeger]
      processors: [batch,probabilistic_sampler,filter/drop_healthcheck]
    traces/k8s:
      receivers: [otlp]
      exporters: [otlphttp/k8s-signoz,otlphttp/k8s-jaeger]
      processors: [batch,probabilistic_sampler,filter/drop_healthcheck]
  batch:
    timeout: 5s
    send_batch_size: ${TRACING_OPENTELEMETRY_COLLECTOR_BATCH_SIZE}
  probabilistic_sampler:
    sampling_percentage: ${TRACING_OPENTELEMETRY_COLLECTOR_SAMPLING_PERCENTAGE}
  filter/drop_healthcheck:
    error_mode: ignore
    traces:
      span:
        - attributes["http.route"] == "healthcheck_readiness_probe"
        - attributes["db.statement"] == "PING" and attributes["db.system"] == "redis"
